name: erfolg
timestamp: 1733829679
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1716537822
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  hero:
    hero-7488: 'Hero block'
  messages:
    system-messages-2609: 'System Messages'
  logo:
    logo-1685: 'Logo / Image'
    logo-5510: 'Logo / Image'
  menu:
    menu-9128: Menu
  social:
    social-3982: Social
  position:
    position-position-6426: Aside
    position-position-4031: Sidebar
  content:
    system-content-6201: 'Page Content'
  verticalmenu:
    verticalmenu-3787: 'Vertical Menu'
    verticalmenu-4213: 'Vertical Menu'
  contact:
    contact-5760: Contact
  totop:
    totop-5508: 'To Top'
  mobile-menu:
    mobile-menu-9613: Mobile-menu
inherit:
  default:
    navigation: navigation
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
    footer: footer
    offcanvas: offcanvas
    system-messages-2609: system-messages-7972
    logo-1685: logo-9608
    menu-9128: menu-6409
    social-3982: social-3171
    position-position-6426: position-position-4734
    system-content-6201: system-content-1587
    position-position-4031: position-position-3949
    logo-5510: logo-9571
    verticalmenu-3787: verticalmenu-3628
    verticalmenu-4213: verticalmenu-6607
    contact-5760: contact-6866
    totop-5508: totop-8670
    mobile-menu-9613: mobile-menu-5697
