name: kontakt
timestamp: 1733829679
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1716537822
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  hero:
    hero-7488: 'Hero block'
  contenttabs:
    contenttabs-2162: 'Content Tabs'
  messages:
    system-messages-5006: 'System Messages'
  logo:
    logo-3175: 'Logo / Image'
    logo-2657: 'Logo / Image'
  menu:
    menu-6829: Menu
  social:
    social-3569: Social
  position:
    position-position-8647: Aside
    position-position-8401: Sidebar
  content:
    system-content-2136: 'Page Content'
  verticalmenu:
    verticalmenu-7625: 'Vertical Menu'
    verticalmenu-8245: 'Vertical Menu'
  contact:
    contact-6101: Contact
  totop:
    totop-2803: 'To Top'
  mobile-menu:
    mobile-menu-9394: Mobile-menu
inherit:
  default:
    navigation: navigation
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
    footer: footer
    offcanvas: offcanvas
    system-messages-5006: system-messages-7972
    logo-3175: logo-9608
    menu-6829: menu-6409
    social-3569: social-3171
    position-position-8647: position-position-4734
    system-content-2136: system-content-1587
    position-position-8401: position-position-3949
    logo-2657: logo-9571
    verticalmenu-7625: verticalmenu-3628
    verticalmenu-8245: verticalmenu-6607
    contact-6101: contact-6866
    totop-2803: totop-8670
    mobile-menu-9394: mobile-menu-5697
