preset: preset1
base:
  background: '#71d154'
navigation:
  background: '#f1493c'
  text-color: '#ffffff'
header:
  background: '#f1493c'
  background-image: ''
  background-overlay: disabled
  text-color: '#ffffff'
