name: kann_sein
timestamp: 1733829679
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1716537822
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  hero:
    hero-7488: 'Hero block'
  messages:
    system-messages-8920: 'System Messages'
  logo:
    logo-3019: 'Logo / Image'
    logo-4187: 'Logo / Image'
  menu:
    menu-7371: Menu
  social:
    social-6786: Social
  position:
    position-position-5788: Aside
    position-position-1523: Sidebar
  content:
    system-content-7738: 'Page Content'
  verticalmenu:
    verticalmenu-9312: 'Vertical Menu'
    verticalmenu-1092: 'Vertical Menu'
  contact:
    contact-2221: Contact
  totop:
    totop-2103: 'To Top'
  mobile-menu:
    mobile-menu-7654: Mobile-menu
inherit:
  default:
    navigation: navigation
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
    footer: footer
    offcanvas: offcanvas
    system-messages-8920: system-messages-7972
    logo-3019: logo-9608
    menu-7371: menu-6409
    social-6786: social-3171
    position-position-5788: position-position-4734
    system-content-7738: system-content-1587
    position-position-1523: position-position-3949
    logo-4187: logo-9571
    verticalmenu-9312: verticalmenu-3628
    verticalmenu-1092: verticalmenu-6607
    contact-2221: contact-6866
    totop-2103: totop-8670
    mobile-menu-7654: mobile-menu-5697
